(() => {
  "use strict";
  let tg = window.Telegram?.WebApp || null;
  const state = { screen: "home", releases: [], profile: null, step: 1, search: "", genre: "all", sort: "newest" };
  const paths = {
    home: '<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M9 21v-7h6v7"/>',
    music: '<path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/>',
    upload: '<path d="M12 16V4m0 0L7 9m5-5 5 5"/><path d="M5 14v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-5"/>',
    user: '<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
    menu: '<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
    search: '<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
    close: '<path d="m6 6 12 12M18 6 6 18"/>',
    arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
    heart: '<path d="M20.8 8.6c0 5.4-8.8 10.4-8.8 10.4S3.2 14 3.2 8.6A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.8 2.2Z"/>',
    star: '<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9z"/>',
    send: '<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>',
    telegram: '<path d="m21 3-4 18-6-6-4-2 14-10Z"/><path d="m11 15 1-5 5-4"/>',
    mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',
    external: '<path d="M14 5h5v5M19 5l-8 8"/><path d="M19 13v5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5"/>',
    shield: '<path d="M12 3 20 6v5c0 5-3.4 8.5-8 10-4.6-1.5-8-5-8-10V6z"/><path d="m8 12 2.5 2.5L16 9"/>'
  };
  const icon = (name, size = 18) => '<svg class="svg-icon" width="' + size + '" height="' + size + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + (paths[name] || paths.music) + "</svg>";
  const esc = (v) => String(v ?? "").replace(/[&<>'"]/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[c]));
  const date = (v) => v ? new Date(v).toLocaleDateString("ru-RU") : "—";
  const initData = () => tg?.initData || window.Telegram?.WebApp?.initData || "";
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  async function api(url, options = {}) {
    const headers = { ...(options.headers || {}), "x-telegram-init-data": initData() };
    if (options.body && typeof options.body !== "string") { headers["content-type"] = "application/json"; options.body = JSON.stringify(options.body); }
    const response = await fetch(url, { ...options, headers });
    const data = await response.json().catch(() => ({}));
    if (!response.ok || data.ok === false) throw new Error(data.error || "Не удалось выполнить запрос");
    return data;
  }
  function toast(text) { const el = $("#toast"); el.textContent = text; el.classList.remove("is-hidden"); clearTimeout(window.__toast); window.__toast = setTimeout(() => el.classList.add("is-hidden"), 3000); }
  function cover(item) { return esc(item.cover || item.raw?.cover || "assets/general.jpg"); }
  function statusText(s) { return ({ approved:"Одобрено", published:"Опубликовано", rejected:"Отклонено", moderation:"На проверке", on_moderation:"На проверке", pending:"Черновик" }[s] || s || "Статус"); }
  function formatRelease(item) { return '<article class="release-card" data-release-id="' + esc(item.id) + '"><div class="cover-wrap"><img src="' + cover(item) + '" alt="" loading="lazy" onerror="this.src=\'assets/general.jpg\'"><span class="status status-' + esc(item.status) + '">' + esc(statusText(item.status)) + "</span></div><div class=\"release-info\"><h3>" + esc(item.title) + "</h3><p>" + esc(item.artist) + "</p><small>ID: " + esc(item.id) + " · " + esc(item.genre || "Музыка") + '</small><div class="card-actions"><button class="card-open">Открыть релиз <span class="icon" data-icon="arrow"></span></button><button class="card-like engage" data-kind="like" data-id="' + esc(item.id) + '" aria-label="Поставить лайк">' + icon("heart", 15) + '</button></div></div></article>'; }
  function renderIcons() { $$("[data-icon]").forEach((el) => { el.innerHTML = icon(el.dataset.icon, el.classList.contains("nav-icon") ? 17 : 18); }); }
  function renderHome() { $("#homeReleases").innerHTML = state.releases.slice(0, 10).map(formatRelease).join("") || '<div class="empty">Пока нет одобренных релизов для витрины.</div>'; renderIcons(); }
  function renderCatalog() { let list = state.releases.filter((x) => (x.title + " " + x.artist + " " + x.genre + " " + x.upc).toLowerCase().includes(state.search.toLowerCase())); if (state.genre !== "all") list = list.filter((x) => x.genre === state.genre); if (state.sort === "title") list.sort((a,b) => a.title.localeCompare(b.title)); $("#catalogGrid").innerHTML = list.map(formatRelease).join("") || '<div class="empty">По этому запросу ничего не найдено.</div>'; renderIcons(); }
  function renderProfile() { const data = state.profile || {}, user = data.user || {}, stats = data.stats || {}; const photo = esc(user.photo_url || "assets/logo.png"); $("#profileContent").innerHTML = '<div class="profile-card"><img src="' + photo + '" onerror="this.src=\'assets/logo.png\'" alt=""><div><small>' + (user.role === "admin" ? "ADMIN ACCOUNT" : "ARTIST ACCOUNT") + "</small><h2>" + esc((user.first_name || "Пользователь") + " " + (user.last_name || "")) + "</h2><p>" + esc(user.username ? "@" + user.username : "Username не указан") + "</p></div><span class=\"role-tag\">" + esc(user.role === "admin" ? "Администратор" : "Артист") + '</span></div><button class="button button-secondary profile-edit" data-edit-profile>' + icon("user", 16) + ' Настроить профиль артиста</button><div class="stats-grid"><div><b>' + (stats.releases || 0) + '</b><small>Релизов</small></div><div><b>' + (stats.listens || 0) + '</b><small>Прослушиваний</small></div><div><b>' + (stats.likes || 0) + '</b><small>Лайков</small></div><div><b>' + (stats.favorites || 0) + '</b><small>Избранное</small></div></div><div class="info-card"><div class="card-heading"><h2>Аккаунт Telegram</h2><span class="status status-approved">' + (user.status === "active" ? "Активен" : esc(user.status || "—")) + '</span></div><p>ID: <b>' + esc(user.telegram_id) + "</b><br>Регистрация: <b>" + date(user.registered_at) + '</b></p></div><div class="info-card"><div class="card-heading"><h2>Мои релизы</h2><button class="link-button" data-screen="submit">Новый релиз</button></div>' + ((data.releases || []).slice(0, 8).map((r) => '<div class="profile-row"><span>' + esc(r.track_name || r.form_payload?.name || "Без названия") + '</span><span class="status status-' + esc(r.status) + '">' + esc(statusText(r.status)) + "</span></div>").join("") || '<p class="muted">Анкет пока нет.</p>') + '</div><div class="info-card"><div class="card-heading"><h2>Достижения и бейджи</h2></div><p class="muted">Награды и достижения будут появляться автоматически.</p></div>' + (data.is_admin ? '<button class="button button-primary full-width" data-screen="admin">Открыть админ-панель</button>' : ""); }
  function switchScreen(screen) { state.screen = screen; $$(".screen").forEach((x) => x.classList.toggle("is-active", x.id === screen)); $$(".nav-item").forEach((x) => x.classList.toggle("is-active", x.dataset.screen === screen)); window.scrollTo({ top: 0, behavior: "smooth" }); if (screen === "catalog") renderCatalog(); if (screen === "profile") loadProfile(); if (screen === "admin") loadAdmin(); renderIcons(); }
  async function loadAdmin() { try { const data = await api("/api/miniapp/platform/admin"); $("#adminContent").innerHTML = '<div class="stats-grid"><div><b>' + data.stats.users + '</b><small>Пользователи</small></div><div><b>' + data.stats.releases + '</b><small>Релизы</small></div><div><b>' + data.stats.comments + '</b><small>Комментарии</small></div><div><b>' + data.stats.payouts + '</b><small>Выплаты</small></div></div><div class="info-card"><div class="card-heading"><h2>Последние заявки</h2><span class="status status-approved">Защищено</span></div>' + (data.forms || []).slice(0, 12).map((x) => '<div class="profile-row"><span>' + esc(x.track_name || "Без названия") + '<small class="muted">' + esc(x.artist_name || "") + '</small></span><span class="status status-' + esc(x.status) + '">' + esc(statusText(x.status)) + '</span></div>').join("") + '</div>'; } catch (e) { $("#adminContent").innerHTML = '<div class="empty">Доступ запрещён или админ-панель ещё не настроена.</div>'; } }
  async function loadProfile() { try { state.profile = await api("/api/miniapp/platform/profile", { method: "POST", body: { init_data: initData() } }); renderProfile(); } catch (e) { console.warn("[CXRNER_AUTH] profile failed", e); $("#profileContent").innerHTML = '<div class="empty">Telegram не передал данные авторизации. Закрой Mini App и открой его кнопкой «Main App» в боте.</div>'; } }
  function openRelease(id) { const item = state.releases.find((x) => x.id === id); if (!item) return; $("#modalContent").innerHTML = '<img class="modal-cover" src="' + cover(item) + '" onerror="this.src=\'assets/general.jpg\'" alt=""><small class="eyebrow">' + esc(item.genre || "РЕЛИЗ") + '</small><h2>' + esc(item.title) + '</h2><p class="artist-name">' + esc(item.artist) + '</p><p class="muted">' + esc(item.description || "Описание релиза появится после публикации.") + '</p><div class="modal-meta"><span>UPC<br><b>' + esc(item.upc || "—") + '</b></span><span>Дата<br><b>' + esc(item.date || "—") + '</b></span><span>Тип<br><b>' + esc(item.type || "single") + "</b></span></div><div class=\"action-row\"><button class=\"button button-primary engage\" data-kind=\"like\" data-id=\"" + esc(item.id) + "\">" + icon("heart", 17) + " Лайк</button><button class=\"button button-secondary engage\" data-kind=\"favorite\" data-id=\"" + esc(item.id) + "\">" + icon("star", 17) + " Сохранить</button></div>";
    $("#releaseModal").classList.remove("is-hidden"); renderIcons(); loadArtistCard(item.telegram_id, item.artist); }
  async function loadArtistCard(telegramId, artistName) { if (!telegramId) return; try { const data = await fetch("/api/miniapp/platform/artist?telegram_id=" + encodeURIComponent(telegramId), { headers: { "x-telegram-init-data": initData() } }).then((response) => response.json()); const artist = data.artist || {}; const badges = (data.badges || []).map((badge) => '<span class="badge-card"><img src="' + esc(badge.image_url) + '" onerror="this.style.display=\'none\'" alt=""><b>' + esc(badge.name) + '</b></span>').join(""); const name = artist.display_name || artistName || "Артист"; const block = '<div class="artist-profile"><img src="' + esc(artist.avatar_url || "assets/logo.png") + '" onerror="this.src=\'assets/logo.png\'" alt=""><div><small>ПРОФИЛЬ АРТИСТА</small><h3>' + esc(name) + '</h3><p>' + esc(artist.bio || "Артист CXRNER MUSIC") + '</p><span class="muted">' + (data.followers || 0) + ' подписчиков</span></div><button class="button button-secondary follow-button" data-follow-id="' + esc(telegramId) + '">' + icon("user", 15) + ' Подписаться</button></div>' + (badges ? '<div class="artist-badges"><small>БЕЙДЖИ АРТИСТА</small><div>' + badges + '</div></div>' : ""); $("#modalContent").insertAdjacentHTML("beforeend", block); renderIcons(); } catch (error) { console.warn("[CXRNER_ARTIST]", error); } }
  function setStep(step) { state.step = step; $$(".form-step").forEach((x) => x.classList.toggle("is-current", Number(x.dataset.formStep) === step)); $$(".step").forEach((x) => x.classList.toggle("is-current", Number(x.dataset.stepIndicator) === step)); }
  function validateStep() { const fields = $$("[data-form-step='" + state.step + "'] [required]"); for (const field of fields) { if (!field.value.trim()) { field.focus(); toast("Заполни обязательное поле"); return false; } } return true; }
  async function submitForm(event) { event.preventDefault(); if (!validateStep()) return; if (state.step < 3) { setStep(state.step + 1); return; } const form = event.currentTarget, data = new FormData(form), val = (name, fallback = ".") => String(data.get(name) || fallback).trim(), type = val("type", ""); if (!type) { setStep(1); toast("Выбери тип релиза"); return; } const payload = { action:"webapp_release_submit", source:"mini_app", version:3, submitted_at:new Date().toISOString(), telegram_id:state.profile?.user?.telegram_id || null, user:state.profile?.user || tg?.initDataUnsafe?.user || null, form:{ type, name:val("name",""), subname:val("subname"), has_lyrics:val("has_lyrics",""), nick:val("nick",""), fio:val("fio",""), date:val("date",""), version:val("version"), genre:val("genre",""), link:val("link",""), yandex:val("yandex"), mat:val("mat",""), promo:val("promo"), comment:val("comment"), tracklist:val("tracklist"), tg:val("tg","") } }; try { const result = await api("/api/webapp/submit", { method:"POST", body:{ reason:"submit_form", source:"mini_app", submitted_at:new Date().toISOString(), payload, initData:initData(), user:tg?.initDataUnsafe?.user || null } }); toast(result.data?.duplicate ? "Такая анкета уже есть." : "Релиз отправлен на модерацию."); form.reset(); setStep(1); switchScreen("profile"); } catch (e) { toast("Не удалось отправить: " + e.message); } }
  async function load() { try { const catalog = await api("/api/miniapp/platform/catalog"); state.releases = catalog.releases || []; const genres = [...new Set(state.releases.map((x) => x.genre).filter(Boolean))].sort(); $("#genreFilter").innerHTML = '<option value="all">Все жанры</option>' + genres.map((x) => '<option value="' + esc(x) + '">' + esc(x) + '</option>').join(""); renderHome(); renderCatalog(); } catch (e) { state.releases = []; renderHome(); renderCatalog(); } await loadProfile(); renderIcons(); $("#loader").classList.add("is-hidden"); $("#app").classList.remove("is-hidden"); }
  document.addEventListener("click", async (event) => { const nav = event.target.closest("[data-screen]"); if (nav) { event.preventDefault(); switchScreen(nav.dataset.screen); return; } if (event.target.closest("[data-close-modal]")) { $("#releaseModal").classList.add("is-hidden"); return; } const edit = event.target.closest("[data-edit-profile]"); if (edit) { const current = state.profile?.user || {}; const displayName = window.prompt("Имя артиста", current.first_name || ""); if (displayName === null) return; const bio = window.prompt("Короткое описание артиста", ""); if (bio === null) return; try { await api("/api/miniapp/platform/artist/profile", { method:"POST", body:{ init_data:initData(), profile:{ display_name:displayName, bio } } }); toast("Профиль сохранён"); } catch (e) { toast("Профиль не сохранён: " + e.message); } return; } const follow = event.target.closest(".follow-button"); if (follow) { try { await api("/api/miniapp/platform/follow", { method:"POST", body:{ init_data:initData(), following_id:follow.dataset.followId, active:true } }); follow.textContent = "Подписка оформлена"; toast("Ты подписался на артиста"); } catch (e) { toast("Не удалось подписаться: " + e.message); } return; } const engage = event.target.closest(".engage"); if (engage) { event.preventDefault(); event.stopPropagation(); try { await api("/api/miniapp/platform/engagement", { method:"POST", body:{ init_data:initData(), release_id:engage.dataset.id, kind:engage.dataset.kind, active:true } }); toast(engage.dataset.kind === "like" ? "Лайк добавлен" : "Сохранено в избранное"); } catch (e) { toast("Лайк не сохранён: " + e.message); } return; } const card = event.target.closest("[data-release-id]"); if (card) { openRelease(card.dataset.releaseId); return; } const clear = event.target.closest("#clearSearch"); if (clear) { $("#catalogSearch").value = ""; state.search = ""; renderCatalog(); } });
  $("#catalogSearch").addEventListener("input", (e) => { state.search = e.target.value; renderCatalog(); }); $("#genreFilter").addEventListener("change", (e) => { state.genre = e.target.value; renderCatalog(); }); $("#sortFilter").addEventListener("change", (e) => { state.sort = e.target.value; renderCatalog(); }); $("#releaseForm").addEventListener("submit", submitForm); document.addEventListener("click", (event) => { if (event.target.closest(".next-step")) { if (validateStep()) setStep(Math.min(3, state.step + 1)); } if (event.target.closest(".prev-step")) setStep(Math.max(1, state.step - 1)); });
  window.addEventListener("load", () => { tg = window.Telegram?.WebApp || tg; tg?.ready(); tg?.expand(); load(); });
})();
