(() => {
  const slug = decodeURIComponent(location.pathname.split('/').filter(Boolean).pop() || '');
  const app = document.getElementById('linkApp');
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const labels = { spotify:'Spotify', apple:'Apple Music', yandex:'Яндекс Музыка', vk:'VK Музыка', youtube:'YouTube Music', deezer:'Deezer', zvuk:'Звук', soundcloud:'SoundCloud' };
  const initials = (name) => ({ spotify:'SP', apple:'AM', yandex:'Я', vk:'VK', youtube:'YT', deezer:'DZ', zvuk:'ЗВ', soundcloud:'SC' }[name] || '↗');
  async function event(type, platform = '') { fetch('/api/miniapp/link/event', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ slug, event_type:type, platform, source:document.referrer || '', device:/Mobi|Android/i.test(navigator.userAgent) ? 'mobile' : 'desktop' }) }).catch(() => {}); }
  function openPlatform(url, platform) { event('click', platform); window.location.href = url; }
  async function load() { const response = await fetch('/api/miniapp/link?slug=' + encodeURIComponent(slug)); const data = await response.json(); if (!response.ok || !data.link) throw new Error(data.error || 'Ссылка не найдена'); const link = data.link; document.title = link.title + ' — ' + link.artist + ' · CXRNER LINK'; app.className = 'link-app theme-' + escapeHtml(link.theme || 'aurora'); const platforms = Object.entries(link.platforms || {}).filter(([,url]) => url).map(([name,url]) => '<a class="platform-link" href="' + escapeHtml(url) + '" data-platform="' + escapeHtml(name) + '"><span class="platform-icon">' + initials(name) + '</span><span>' + escapeHtml(labels[name] || name) + '</span><span class="external-mark">↗</span></a>').join(''); const extras = (link.extra_links || []).map((item) => '<a class="extra-link" href="' + escapeHtml(item.url) + '" data-platform="extra"><span class="platform-icon">↗</span><span>' + escapeHtml(item.label) + '</span><span class="external-mark">↗</span></a>').join(''); const first = Object.entries(link.platforms || {}).find(([,url]) => url)?.[1] || '#'; app.innerHTML = '<div class="link-top"><img src="/assets/logo.png" alt=""> CXRNER LINK</div><div class="link-cover"><img src="' + escapeHtml(link.cover_url || '/assets/general.jpg') + '" onerror="this.src=\'/assets/general.jpg\'" alt="' + escapeHtml(link.title) + '"></div><h1>' + escapeHtml(link.title) + '</h1><p class="link-artist">' + escapeHtml(link.artist) + '</p><p class="link-meta">' + escapeHtml([link.genre,link.release_date].filter(Boolean).join(' · ')) + '</p><a class="link-listen" href="' + escapeHtml(first) + '" data-platform="listen">▶&nbsp; Слушать</a>' + (platforms ? '<span class="section-label">МУЗЫКАЛЬНЫЕ ПЛОЩАДКИ</span><div class="platform-grid">' + platforms + '</div>' : '<p class="link-meta">Площадки пока не добавлены.</p>') + (extras ? '<span class="section-label">ЕЩЁ ОТ АРТИСТА</span><div class="extra-grid">' + extras + '</div>' : '') + '<div class="share-row"><button id="shareLink">Поделиться</button><button id="copyLink">Скопировать</button></div><div class="link-footer">CXRNER MUSIC · CXRNER LINK</div>'; app.querySelectorAll('[data-platform]').forEach((node) => node.addEventListener('click', () => event('click', node.dataset.platform))); document.getElementById('shareLink').onclick = async () => { if (navigator.share) await navigator.share({ title:link.title, text:link.artist, url:location.href }); else { await navigator.clipboard?.writeText(location.href); alert('Ссылка скопирована'); } }; document.getElementById('copyLink').onclick = async () => { await navigator.clipboard?.writeText(location.href); alert('Ссылка скопирована'); }; event('view'); setTimeout(() => document.getElementById('linkSplash')?.remove(), 1050); }
  load().catch((error) => { document.getElementById('linkSplash')?.remove(); app.className = 'link-app'; app.innerHTML = '<div class="link-error"><h1>Ссылка не найдена</h1><p>' + escapeHtml(error.message) + '</p></div>'; });
})();
